### ISSUE TITLE
ziet er leuk uit, mis nog wel waar je alle info vandaan haalt? zelf plaatjes tekenen?

### ISSUE THREAD

**Issue by stgm** [RosannevanderPol/Project#2]

**Comment by RosannevanderPol** [comment]
De categorieën en woorden verzin ik zelf... en de plaatjes, das idd een
goeie! Die zal ik idd zelf maken. Of kan ik ook plaatjes van internet halen
met bronvermelding?
Op 5 jan. 2016 10:36 schreef "Martijn Stegeman" notifications@github.com:

**Comment by stgm** [comment]
Dat is ook prima :-) Kijk er even naar en doe alvast een suggestie in je proposal
